### ISSUE TITLE
Getting CORS error while fetching

### ISSUE THREAD

**Issue by Aashu-007** [HeT-Delwadiya/Inshorts-news-api#1]
The console shows the error below :-
I have also attached the screenshot of the error.

Access to fetch at 'https://inshorts.com/en/read/technology' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled
![inshorts error](https://user-images.githubusercontent.com/79891394/178098547-8598c67d-0672-4bdf-b591-caaee744dd9a.png)
.

**Comment by het-delwadiya** [comment]
Its because the browser sets origin in every HTTP request and inshorts backend doesn't allow other origins to access resources. so, you have to use this package on the backend. Don't use this package on front end directly.

**Comment by Aashu-007** [comment]
How to use in backend. Actually I am building a react news app, so like how to use it in backend, if you could provide some tutorial video references I would be grateful.

**Comment by het-delwadiya** [comment]
I already made a backend for it. You can use it directly - https://github.com/HeT-Delwadiya/NewsClub-Backend. Just spin up this backend server and use the APIs created in this backend to get data.

**Comment by Aashu-007** [comment]
Ok I'll try
