### ISSUE TITLE
News API is not working properly 

### ISSUE THREAD

**Issue by devajaypatidar** [HeT-Delwadiya/Inshorts-news-api#2]
The index js is the line number 46  showing cannot read the property of null

**Comment by het-delwadiya** [comment]
They have updated the response of their API. Need to work on the updated html response to scrape the data. Might take some days as hard to find time these days. Feel free to contribute :)

**Comment by het-delwadiya** [comment]
@devajaypatidar Hey I have updated the package to work with updated Inshorts APIs. Please let me know if its working for you too.

**Comment by het-delwadiya** [comment]
Closing this issue as the fix is working as expected.
